#%RAML 1.0 DataType
properties:
  id:
    type: string
    description: Universal identifier for users
    example: "04d2d0ea-f85b-4736-ac38-0f02af714ae1"
    required: false
  name:
    type: string
    description: User full name
    example: "John Doe"
    required: false
  status:
    type: integer
    description: Universal identifier for status
    example: 8
    required: false
  phone:
    type: string
    description: User phone with local and global codes
    example: "+584169051604"
    required: false
  createdAt:
    type: string
    description: Cration date and time
    example: "2016-02-28T16:41:41.090Z"
    required: false
  updatedAt:
    type: string
    description: Update date and time
    example: "2016-02-28T16:41:41.090Z"
    required: false