#%RAML 1.0 DataType
properties: 
  code:
    type: string
    description: error code assigned
    example: "400"
  message:
    type: string
    description: Error description
    example: "An error occurred while trying to proccess request"