#%RAML 1.0 DataType
properties: 
  success:
    type: boolean
    description: Operation status
    example: true
  message:
    type: string
    description: Additional Message
    examples:
      UpdatedSuccessfully: Successfully Updated
      AddedSuccessfully: Successfully Added